openapi: 3.0.0
info:
  title: FlightApi_swagger
  version: 1.0.0
servers:
  - url: http://{{endpoint}}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /:
    get:
      tags:
        - default
      summary: Home
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    get:
      tags:
        - default
      summary: Login
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /Cities:
    get:
      tags:
        - default
      summary: GetCityByCode
      parameters:
        - name: CityCode
          in: query
          schema:
            type: string
          example: PAR
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:35:38 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '46'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - CityInitials: PAR
                  CityName: Paris
    post:
      tags:
        - default
      summary: AddCity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                CityInitials: CMN
                CityName: Casablanca
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer: {{token}}'
      responses:
        '201':
          description: CREATED
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:35:52 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '49'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                CityInitials: CMN
                CityName: Casablanca
  /Cities/CMN:
    patch:
      tags:
        - default
      summary: UpdateCity
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n   \"CityInitials\":\"CMN\",\r\n  
                \"CityName\":\"Casablanca\"\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer: {{token}}'
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:35:59 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '49'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                CityInitials: CMN
                CityName: Casablanca
    delete:
      tags:
        - default
      summary: DeleteCity
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer: {{token}}'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:36:06 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '29'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                'true': 'City deleted CMN '
  /RandomFlights:
    get:
      tags:
        - default
      summary: RandomFlights
      parameters:
        - name: Count
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:36:23 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '568'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - Airline: NW
                  ArrivalCity: London
                  ArrivalTime: 05:31 PM
                  DepartureCity: Paris
                  DepartureTime: 03:50 PM
                  FlightNumber: 11120
                  Price: 147.4
                  PriceFirst: 176.88
                  PriceBusiness: 191.62
                  SeatsAvailable: 250
                  DayOfWeek: Friday
                  Date: '2023-02-10'
                - Airline: LH
                  ArrivalCity: Zurich
                  ArrivalTime: 03:21 PM
                  DepartureCity: San Francisco
                  DepartureTime: 02:23 PM
                  FlightNumber: 14468
                  Price: 167.8
                  PriceFirst: 201.36
                  PriceBusiness: 218.14
                  SeatsAvailable: 250
                  DayOfWeek: Sunday
                  Date: '2023-01-29'
  /Flights/{FlightNumber}:
    get:
      tags:
        - default
      summary: GetFlight
      parameters:
        - name: FlightNumber
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:36:40 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '256'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                Airline: NW
                ArrivalCity: London
                ArrivalTime: 05:31 PM
                DepartureCity: Paris
                DepartureTime: 03:50 PM
                FlightNumber: 11120
                Price: 147.4
                PriceFirst: 176.88
                PriceBusiness: 191.62
                SeatsAvailable: 250
                DayOfWeek: Friday
    delete:
      tags:
        - default
      summary: DeleteFlight
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer: {{token}}'
        - name: FlightNumber
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:37:04 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '34'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                'true': 'Flight deleted 100000 '
  /Flights:
    get:
      tags:
        - default
      summary: SearchFlights
      parameters:
        - name: DepartureCity
          in: query
          schema:
            type: string
          example: Paris
        - name: ArrivalCity
          in: query
          schema:
            type: string
          example: London
        - name: Date
          in: query
          schema:
            type: string
          example: '2023-11-16'
      responses:
        '500':
          description: INTERNAL SERVER ERROR
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:39:27 GMT
            Content-Type:
              schema:
                type: string
                example: text/html; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '265'
            Connection:
              schema:
                type: string
                example: close
          content:
            text/plain:
              schema:
                type: string
              example: >-
                <!doctype html><html lang=en><title>500 Internal Server
                Error</title><h1>Internal Server Error</h1><p>The server
                encountered an internal error and was unable to complete your
                request. Either the server is overloaded or there is an error in
                the application.</p>
    post:
      tags:
        - default
      summary: AddFlight
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n    \"Airline\": \"RAM\",\r\n    \"ArrivalCity\":
                \"Paris\",\r\n    \"ArrivalInitials\": \"PAR\",\r\n   
                \"ArrivalTime\": \"11:00 AM\",\r\n    \"DepartureCity\":
                \"Denver\",\r\n    \"DepartureInitials\": \"DEN\",\r\n   
                \"DepartureTime\": \"23:23 AM\",\r\n    \"Price\": 23.0,\r\n   
                \"PriceFirst\": 233.0,\r\n    \"PriceBusiness\": 2333.0,\r\n   
                \"SeatsAvailable\": 10,\r\n    \"DayOfWeek\": \"Monday\"\r\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: 'Bearer: {{token}}'
      responses:
        '201':
          description: CREATED
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:36:52 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '256'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                Airline: RAM
                ArrivalCity: Paris
                ArrivalTime: 11:00 AM
                DepartureCity: Casablanca
                DepartureTime: 08:00 AM
                FlightNumber: 100000
                Price: 112
                PriceFirst: 126
                PriceBusiness: 150
                SeatsAvailable: 100
                DayOfWeek: Monday
  /FlightOrders:
    post:
      tags:
        - default
      summary: BookFight
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                DepartureDate: '2023-11-16'
                FlightNumber: 10519
                CustomerName: ONEPOINT
                NumberOfTickets: 2
                Class: First
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteAllOrders
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:39:52 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '1707'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                - Class: Business
                  CustomerName: John Doe
                  DepartureDate: 2014-7-11 7:59
                  FlightNumber: 6232
                  NumberOfTickets: 1
                  OrderNumber: 1
                  TotalPrice: 135.2
                - Class: First
                  CustomerName: Fred Smith
                  DepartureDate: 2014-7-12 7:59
                  FlightNumber: 4295
                  NumberOfTickets: 3
                  OrderNumber: 2
                  TotalPrice: 1165.68
                - Class: Economy
                  CustomerName: Mary Parker
                  DepartureDate: 2014-7-13 7:59
                  FlightNumber: 4194
                  NumberOfTickets: 5
                  OrderNumber: 3
                  TotalPrice: 803
                - Class: First
                  CustomerName: Jon Baker
                  DepartureDate: 2014-7-14 7:59
                  FlightNumber: 4219
                  NumberOfTickets: 4
                  OrderNumber: 4
                  TotalPrice: 776.16
                - Class: Business
                  CustomerName: Kim Smith
                  DepartureDate: 2014-7-15 19:59
                  FlightNumber: 6195
                  NumberOfTickets: 6
                  OrderNumber: 5
                  TotalPrice: 1376.46
                - Class: First
                  CustomerName: Joe Shmoe
                  DepartureDate: 2014-7-16 19:59
                  FlightNumber: 4210
                  NumberOfTickets: 1
                  OrderNumber: 6
                  TotalPrice: 202.44
                - Class: Business
                  CustomerName: Jane Doe
                  DepartureDate: 2014-7-17 19:59
                  FlightNumber: 3291
                  NumberOfTickets: 9
                  OrderNumber: 7
                  TotalPrice: 1175.85
                - Class: First
                  CustomerName: Bob Johnson
                  DepartureDate: 2014-7-18 19:59
                  FlightNumber: 6218
                  NumberOfTickets: 2
                  OrderNumber: 8
                  TotalPrice: 425.92
                - Class: Business
                  CustomerName: Jack Barnes
                  DepartureDate: 2014-7-19 19:59
                  FlightNumber: 6232
                  NumberOfTickets: 1
                  OrderNumber: 9
                  TotalPrice: 135.2
                - Class: Economy
                  CustomerName: Jane Hansen
                  DepartureDate: 2014-7-20 19:59
                  FlightNumber: 4214
                  NumberOfTickets: 2
                  OrderNumber: 10
                  TotalPrice: 321.6
  /FlightOrders/{OrderNumber}:
    patch:
      tags:
        - default
      summary: UpdateOrder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                DepartureDate: '2023-11-16'
                FlightNumber: 10519
                CustomerName: ONEPOINT
                NumberOfTickets: 10
                Class: Business
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: OrderNumber
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:39:40 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '165'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                Class: First
                CustomerName: IMHAH
                DepartureDate: 2023-1-21 08:00
                FlightNumber: 99558
                NumberOfTickets: 3
                OrderNumber: 81
                TotalPrice: 666.72
    get:
      tags:
        - default
      summary: GetOrder
      parameters:
        - name: OrderNumber
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:39:40 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '165'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                Class: First
                CustomerName: IMHAH
                DepartureDate: 2023-1-21 08:00
                FlightNumber: 99558
                NumberOfTickets: 3
                OrderNumber: 81
                TotalPrice: 666.72
    delete:
      tags:
        - default
      summary: DeleteOrder
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: OrderNumber
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Werkzeug/2.2.2 Python/3.11.1
            Date:
              schema:
                type: string
                example: Wed, 28 Dec 2022 00:39:46 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '29'
            Connection:
              schema:
                type: string
                example: close
          content:
            application/json:
              schema:
                type: object
              example:
                'true': 'Order deleted 81 '
